# Generated by Django 3.0.4 on 2020-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20200412_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderTotal',
            field=models.IntegerField(default=0),
        ),
    ]
