# Generated by Django 3.0.3 on 2020-04-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(default='Proccessing', max_length=256),
        ),
    ]
