# Generated by Django 3.0.3 on 2020-04-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_order_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderState',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
