# Generated by Django 3.0.3 on 2020-04-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20200412_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_buyLink',
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(default='Failed', max_length=256),
        ),
    ]
